name: ci

on:
  push:
    branches: main

jobs:
  build-and-push:
    name: Build and Push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            alejandro945/rick-morty:${{ github.sha }}
  deploy-to-cluster:
    name: Deploy to Cluster
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - 
        name: Deploy to Azure Cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment.apps/rick-morty-app-deployment rick-morty-app=alejandro945/rick-morty:${{ github.sha }}
      - 
        name: Verify Deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0 # specify kubectl binary version explicitly
          binaries-url: "https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl" # specify the download url explicitly
          command: rollout status deployment.apps/rick-morty-app-deployment
    