name: ci

on:
  push:
    branches: main

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2

      - 
        name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alejandro945/rick-morty
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}

      - 
        name: Deploy to cluster in azure
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/rick-morty-app-deployment rick-morty-app=alejandro945/rick-morty:latest
      - 
        name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0 # specify kubectl binary version explicitly
          binaries-url: "https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl" # specify the download url explicitly
          command: rollout status deployment/rick-morty-app-deployment
    